import { markdownToTelegramHtml, splitMarkdown, TELEGRAM_LIMIT } from "./format.ts";

interface SendOptions {
  parse_mode?: "HTML";
  message_thread_id?: number;
  reply_parameters?: { message_id: number; allow_sending_without_reply?: boolean };
  link_preview_options?: { is_disabled?: boolean };
}

/** The two Bot API calls the streamer needs; grammY's `bot.api` satisfies this. */
export interface MessageApi {
  sendMessage(chatId: number, text: string, other?: SendOptions): Promise<{ message_id: number }>;
  editMessageText(chatId: number, messageId: number, text: string, other?: SendOptions): Promise<unknown>;
  /** Private chats: a temporary draft bubble while the answer is generated (Bot API sendMessageDraft). */
  sendMessageDraft?(chatId: number, draftId: number, text: string, other?: { can_stop?: boolean }): Promise<unknown>;
}

export interface StreamerOptions {
  replyTo?: number;
  /** Forum topic to post in (omit for normal chats and the General topic). */
  threadId?: number;
  /** Minimum time between preview edits; Telegram rate-limits edits per chat. */
  throttleMs?: number;
  /** Don't send the first preview until this many characters exist (avoids a 1-word ping). */
  minInitialChars?: number;
  /**
   * Private chats: show the answer as a native draft (with Telegram's Stop button)
   * instead of sending and editing a message. The final answer is still sent as messages.
   */
  draftId?: number;
}

const MAX_PREVIEW_FAILURES = 3;
const NO_PREVIEW = { is_disabled: true };

/**
 * Shows a reply while it is generated by sending one message and editing it at
 * most once per `throttleMs` (plain text), then replaces it with the formatted
 * final answer, splitting into more messages when it is too long.
 * Works the same in private chats and groups.
 */
export class ReplyStreamer {
  readonly #api: MessageApi;
  readonly #chatId: number;
  readonly #replyTo: number | undefined;
  readonly #threadId: number | undefined;
  readonly #throttleMs: number;
  readonly #minInitialChars: number;
  #messageId: number | undefined;
  #latest = "";
  #shown = "";
  #timer: ReturnType<typeof setTimeout> | undefined;
  #flushing: Promise<void> = Promise.resolve();
  #failures = 0;
  #finished = false;
  readonly #draftId: number | undefined;

  constructor(api: MessageApi, chatId: number, options: StreamerOptions = {}) {
    this.#api = api;
    this.#chatId = chatId;
    this.#replyTo = options.replyTo;
    this.#threadId = options.threadId || undefined;
    this.#throttleMs = options.throttleMs ?? 1000;
    this.#minInitialChars = options.minInitialChars ?? 24;
    this.#draftId = options.draftId && this.#api.sendMessageDraft ? options.draftId : undefined;
  }

  /** Drafts: show Telegram's "Thinking…" bubble (with Stop) right away. */
  async start(): Promise<void> {
    if (this.#draftId === undefined) return;
    await this.#api.sendMessageDraft!(this.#chatId, this.#draftId, "", { can_stop: true }).catch(() => this.#failures++);
  }

  /** Whether this reply streams as a draft (so the caller needn't show "typing…"). */
  get usesDraft(): boolean {
    return this.#draftId !== undefined && this.#failures < MAX_PREVIEW_FAILURES;
  }

  /** Report the full text generated so far. Cheap to call on every token. */
  update(text: string): void {
    this.#latest = text;
    if (this.#finished || this.#timer || this.#failures >= MAX_PREVIEW_FAILURES) return;
    this.#timer = setTimeout(() => {
      this.#timer = undefined;
      this.#flushing = this.#flushing.then(() => this.#flushPreview());
    }, this.#throttleMs);
  }

  /** Replace the preview with the final formatted reply. Returns the ids of all messages used. */
  async finish(markdown: string): Promise<number[]> {
    this.#finished = true;
    clearTimeout(this.#timer);
    this.#timer = undefined;
    await this.#flushing;
    const chunks = splitMarkdown(markdown);
    if (chunks.length === 0) chunks.push("(empty reply)");
    const ids: number[] = [];
    for (const [index, chunk] of chunks.entries()) {
      const html = markdownToTelegramHtml(chunk);
      if (index === 0 && this.#messageId !== undefined) {
        await this.#editFormatted(this.#messageId, html, chunk);
        ids.push(this.#messageId);
      } else {
        ids.push(await this.#sendFormatted(html, chunk, index === 0 ? this.#replyTo : ids[ids.length - 1]));
      }
    }
    return ids;
  }

  /** End with a plain error notice instead of a reply. */
  async fail(notice: string): Promise<void> {
    this.#finished = true;
    clearTimeout(this.#timer);
    await this.#flushing;
    const partial = this.#latest.trim();
    const text = partial ? `${partial}\n\n⚠️ ${notice}` : `⚠️ ${notice}`;
    await this.finish(text);
  }

  async #flushPreview(): Promise<void> {
    if (this.#finished) return;
    if (this.#draftId !== undefined) {
      const preview = previewText(this.#latest);
      if (!preview || preview === this.#shown) return;
      try {
        await this.#api.sendMessageDraft!(this.#chatId, this.#draftId, preview, { can_stop: true });
        this.#shown = preview;
        this.#failures = 0;
      } catch {
        this.#failures++;
      }
      return;
    }
    if (this.#messageId === undefined && this.#latest.trim().length < this.#minInitialChars) return;
    const preview = previewText(this.#latest);
    if (preview === this.#shown) return;
    try {
      if (this.#messageId === undefined) {
        const sent = await this.#api.sendMessage(this.#chatId, preview, this.#sendOptions(this.#replyTo));
        this.#messageId = sent.message_id;
      } else {
        await this.#api.editMessageText(this.#chatId, this.#messageId, preview, { link_preview_options: NO_PREVIEW });
      }
      this.#shown = preview;
      this.#failures = 0;
    } catch (error) {
      if (!isNotModified(error)) this.#failures++;
    }
  }

  async #sendFormatted(html: string, plain: string, replyTo: number | undefined): Promise<number> {
    try {
      const sent = await this.#api.sendMessage(this.#chatId, html, { ...this.#sendOptions(replyTo), parse_mode: "HTML" });
      return sent.message_id;
    } catch (error) {
      if (!isParseError(error)) throw error;
      const sent = await this.#api.sendMessage(this.#chatId, plain.slice(0, TELEGRAM_LIMIT), this.#sendOptions(replyTo));
      return sent.message_id;
    }
  }

  async #editFormatted(messageId: number, html: string, plain: string): Promise<void> {
    try {
      await this.#api.editMessageText(this.#chatId, messageId, html, { parse_mode: "HTML", link_preview_options: NO_PREVIEW });
    } catch (error) {
      if (isNotModified(error)) return;
      if (!isParseError(error)) throw error;
      try {
        await this.#api.editMessageText(this.#chatId, messageId, plain.slice(0, TELEGRAM_LIMIT), {
          link_preview_options: NO_PREVIEW,
        });
      } catch (fallbackError) {
        if (!isNotModified(fallbackError)) throw fallbackError;
      }
    }
  }

  #sendOptions(replyTo: number | undefined): SendOptions {
    return {
      link_preview_options: NO_PREVIEW,
      ...(this.#threadId !== undefined ? { message_thread_id: this.#threadId } : {}),
      ...(replyTo !== undefined ? { reply_parameters: { message_id: replyTo, allow_sending_without_reply: true } } : {}),
    };
  }
}

/** Plain-text preview that always fits in one Telegram message. */
export function previewText(text: string): string {
  const trimmed = text.trim();
  return trimmed.length > TELEGRAM_LIMIT - 2 ? `${trimmed.slice(0, TELEGRAM_LIMIT - 2)} …` : trimmed;
}

function description(error: unknown): string {
  const value = (error as { description?: unknown; message?: unknown } | null) ?? {};
  return String(value.description ?? value.message ?? "");
}

function isNotModified(error: unknown): boolean {
  return /message is not modified/i.test(description(error));
}

function isParseError(error: unknown): boolean {
  return /can't parse entities|unsupported start tag|can't find end tag/i.test(description(error));
}
